#ifndef QTCREATORDARG_GLOBAL_HPP
#define QTCREATORDARG_GLOBAL_HPP

#include <QtGlobal>

#if defined(QTCREATORDARG_LIBRARY)
#  define QTCREATORDARGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCREATORDARGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCREATORDARG_GLOBAL_H

